import Foundation

/// CRC-16/CCITT (polynomial `0x1021`, initial value `0x0000`) as used by the
/// HP Prime link protocol.
///
/// The reference implementation (`libhpcalcs/src/prime_cmd.c`, `crc16_block`)
/// uses a 256-entry lookup table that is exactly the one generated by shifting
/// the `0x1021` polynomial. The table is generated here rather than transcribed
/// so it cannot drift, and `HPCRC16Tests` cross-checks it against the C
/// implementation.
public enum HPCRC16 {
    /// Lookup table for the CCITT CRC-16 polynomial.
    static let table: [UInt16] = (0..<256).map { index -> UInt16 in
        var crc = UInt16(index) << 8
        for _ in 0..<8 {
            crc = (crc & 0x8000) != 0 ? (crc << 1) ^ 0x1021 : crc << 1
        }
        return crc
    }

    /// Computes the CRC-16/CCITT checksum of `bytes`.
    public static func checksum<Bytes: Sequence>(_ bytes: Bytes) -> UInt16 where Bytes.Element == UInt8 {
        var crc: UInt16 = 0
        for byte in bytes {
            crc = table[Int((crc >> 8) ^ UInt16(byte))] ^ (crc << 8)
        }
        return crc
    }

    /// Computes the checksum over a slice of `bytes`, used where the protocol
    /// excludes a header or trailer from the checksummed region.
    public static func checksum<Bytes: Collection>(
        _ bytes: Bytes,
        range: Range<Int>
    ) -> UInt16 where Bytes.Element == UInt8 {
        var crc: UInt16 = 0
        var index = range.lowerBound
        while index < range.upperBound {
            crc = table[Int((crc >> 8) ^ UInt16(bytes[bytes.index(bytes.startIndex, offsetBy: index)]))] ^ (crc << 8)
            index += 1
        }
        return crc
    }

    /// Zeroes the checksum field wherever it falls inside the region being
    /// checksummed.
    ///
    /// The protocol's own rule is to read the checksum bytes as zero while
    /// computing them. A frame can be short enough that only part of the field —
    /// or none of it — lies within the covered region, so each byte is cleared
    /// independently. Clearing unconditionally would either read out of bounds or
    /// leave a stale byte in the calculation, and either would make the checksum
    /// disagree with the calculator's.
    static func clearChecksumField(_ covered: inout [UInt8], at offsets: [Int]) {
        for offset in offsets where covered.indices.contains(offset) {
            covered[offset] = 0
        }
    }
}
